version: '3.7'

networks:
  webappnet:
    external: true
    name: localdev

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: service-web
    networks:
    - webappnet
    restart: on-failure
    environment:
      VIRTUAL_HOST: test.docker
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: service-app
    networks:
    - webappnet
    restart: on-failure